name: shop_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.10+10

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  url_launcher: ^6.1.7
  random_string: ^2.3.1
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.1
  firebase_core: ^2.25.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.3
  firebase_messaging: ^14.7.5
  awesome_snackbar_content:
  line_icons: ^2.0.3
  font_awesome_icon_class: ^0.0.6
  geolocator: ^9.0.2
  flutter_local_notifications: ^17.0.0
  whatsapp_unilink: ^2.0.0
  google_maps_flutter: ^2.5.0
  geocoding:
  google_sign_in: ^6.2.1
  get: ^4.6.6
  get_it: ^8.2.0
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  flutter_carousel_slider: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_onboarding_slider: ^1.0.10
  http: ^0.13.5
  change_app_package_name: ^1.0.0
  googleapis_auth: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/yamaLogo2.png"
  remove_alpha: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: fs_albert
      fonts:
        - asset: assets/fonts/fs_albert.ttf
          weight: 400
    - family: Inter18pt
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
    - family: Inter28pt
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
          weight: 100
          style: italic
